name: Extraction Data BRVM

on:
  schedule:
    - cron: '*/5 * * * *' #'15 16 * * 1-5' # Runs at 18:22 UTC, Monday to Friday
  workflow_dispatch:

jobs:
  extract-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run extraction script
        run: python brvm-extract-save.py

      - name: Commit and push CSV file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add brvm-data/*.csv
          git commit -m "Update CSV data from extraction workflow" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          # Use the default GITHUB_TOKEN for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CSV file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: brvm-csv
          path: brvm-data/*.csv
