name: Extraction Data BRVM

on:
  schedule:
    - cron: '22 18 * * 1-5' # Runs at 18:22 UTC, Monday to Friday
  workflow_dispatch:

jobs:
  extract-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run extraction script
        run: python brvm-extract-save.py

      - name: Upload CSV file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: brvm-csv
          path: brvm-data/*.csv
